name: Compilar Kernel Moto G200

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Compilar com Dabao Action
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/LineageOS/android_kernel_motorola_sm7325
          kernel-branch: lineage-22.1
          config: vendor/xpeng_defconfig # Corrigido para o codenome real do seu celular!
          arch: arm64
          android-version: 14
          ksu: true
          ksu-other: true
          ksu-url: https://github.com/resukiii/resukiSU
          anykernel3: true
          
