name: Missao Reconhecimento G200

on:
  workflow_dispatch:

jobs:
  investigar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o Repositorio da LineageOS
        run: git clone --depth 1 -b lineage-22.1 https://github.com/LineageOS/android_kernel_motorola_sm7325.git kernel

      - name: 🕵️ Descobrir Nome do Arquivo
        run: |
          echo "=== PROCURANDO TODOS OS ARQUIVOS DEFCONFIG ==="
          find kernel/arch/arm64/configs/ -type f -name "*defconfig*"
          
