name: Compilar Kernel Moto G200

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-22.04 # Força o uso do Ubuntu 22.04 para garantir compatibilidade com os scripts do Kernel 5.4
    steps:
      - name: Compilar com Dabao Action
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/LineageOS/android_kernel_motorola_sm7325
          kernel-branch: lineage-22.1
          config: vendor/lahaina-qgki_defconfig
          arch: arm64
          android-version: 13
          ksu: true
          ksu-other: true
          ksu-url: https://github.com/ReSukiSU/ReSukiSU
          anykernel3: true
          
